### PR TITLE
Deep Learning SMS spam Detection Model

### PR DESCRIPTION
**Pull request by Joe-brands**
In this notebook, I've tried to build an SMS spam detection model with Deep Learning. We may need to build a web/mobile application which can be built in Python using the Flask framework. Then we will work with the Twilio SMS API so that we’ll be able to classify SMS messages sent to a particular phone number registered to a Twilio account.

So let's look at the direction we want to take on this project.

### CODE REVIEW

**Review by sharonibejih — COMMENTED** [review]
Joe, this was quite good. 
I need only a few clarifications:
- Why did you work with a max length of 8words. Did you initially find out the maximum length of words you had after the text_to_sequence before making that decision? I am asking because spam messages are usually long, and I am wondering if the model will work well in such situations.
- Secondly, maybe you use 70:30, let everyone have a uniform train-test ratio.

Thank you!

**Comment by osabobo** [comment]
Your suggestion has been noted.

**Comment by Joe-brands** [comment]
the 8 word lenght is optional, you choose maybe 7 or 6 or even 9. The we can use 70:30 slip

**Comment by Joe-brands** [comment]
Then we can use 70:30 split i meant above

**Comment by sharonibejih** [comment]
> the 8 word lenght is optional, you choose maybe 7 or 6 or even 9. The we can use 70:30 slip

Yeah, in line with that, I am suggesting you find out what the maximum length of your text_to_sequence is for the rows, and maybe the minimum too. This will enable you get a more accommodating threshold rather than 8/9. This is because 8 words are just too short for an sms. It wouldn't make it bogus for any form of long spam messages, as anything aside the first 8 words will automatically be zero. Since there is no luxury of time, it will be nice you do the corrections yourself along with the 70:30 ratio and upload again for review.  Your work looks good.

As for your project suggestion, please don't forget to add it on the google doc. Voting will start midnight.

**Pull request closed without merging**
